### ISSUE TITLE
PIXY2 안정화

### ISSUE THREAD

**Issue by joochanung** [joochanung/FCS#1]

**Comment by GyeongminJang** [comment]
1. pixy2 실행하면서 생기는 문제점이 좌우 회전 서보모터가 불안정하게 물체를 추적한다는 점이다.
2. 이것을 수정하기 위해 좌우 서보모터에 필터링을 거칠 예정
3. pixy2 추적 과정을 최대한 라이브러리 없이 하려고 했으나, 오류가 너무 많이 아직 못한 상태.
