### ISSUE TITLE
TIMER0 vs TIMER1

### ISSUE THREAD

**Issue by GyeongminJang** [joochanung/FCS#4]
TIMER0 -> 8bit timer / counter
TIMER1 -> 16bit timer / counter

 4개의 DC 모터에서 ENA, ENB 핀에 꽂은 핀의 정보다 TIMER0과 TIMER1이다. 그런데 위에 보다시피 TIMER0과 TIMER1에서 bit 개수 차이가 있기에 OCRnx 설정에서 다르게 설정해야 한다.
OCR0x = 255   vs   OCR1x = 511 -> 이 값을 다르게 설정하여 양측 DC 모터의 속도를 일정하게 하도록 만듦.

**Comment by GyeongminJang** [comment]
Master_HC-05와 Slave 아두이노 코드 수정 (SPI 라이브러리 없이 구현)

**Comment by OhJGyun** [comment]
TIMER1 -> 16bit timer / counter
